import type { EndpointModel, NormalizedSpec } from './model';
import type { GeneratedFile } from '../../types';
import { toCamelCase, toPascalCase } from './naming';

export function generateReadme(spec: NormalizedSpec): GeneratedFile {
  const byTag = new Map<string, EndpointModel[]>();
  for (const ep of spec.endpoints) {
    const list = byTag.get(ep.tag) ?? [];
    list.push(ep);
    byTag.set(ep.tag, list);
  }

  const usageSections = Array.from(byTag.entries()).map(([tag, endpoints]) => {
    const queryEp = endpoints.find((e) => e.method === 'get');
    const mutationEp = endpoints.find((e) => e.method !== 'get');
    const lines = [`### ${toPascalCase(tag)}`, ''];
    if (queryEp) {
      lines.push(
        '```tsx',
        `import { use${toPascalCase(queryEp.operationId)} } from './hooks/${toCamelCase(tag)}';`,
        '',
        `function Example() {`,
        `  const { data, isLoading } = use${toPascalCase(queryEp.operationId)}(${queryEp.pathParams.map((p) => defaultArgLiteral(p.tsType)).join(', ')});`,
        `  // ...`,
        `}`,
        '```',
        ''
      );
    }
    if (mutationEp) {
      lines.push(
        '```tsx',
        `import { use${toPascalCase(mutationEp.operationId)} } from './hooks/${toCamelCase(tag)}';`,
        '',
        `function Example() {`,
        `  const { mutate } = use${toPascalCase(mutationEp.operationId)}();`,
        `  // mutate(...)`,
        `}`,
        '```'
      );
    }
    return lines.join('\n');
  });

  const hasGraphQL = spec.endpoints.some((e) => e.graphql);

  const content = `# ${spec.title} — Generated Integration

Generated by a deterministic, template-based pipeline (no AI, no API key required).
Re-run generation any time the spec changes — output is reproducible.

## Installation

\`\`\`bash
npm install axios zod @tanstack/react-query msw
\`\`\`

## Environment Variables

\`\`\`bash
# .env.local
NEXT_PUBLIC_API_BASE_URL=${spec.baseUrl ?? 'https://api.example.com'}
\`\`\`
${hasGraphQL ? '\nPoint this at your GraphQL endpoint directly (e.g. `https://api.example.com/graphql`) — every generated service method POSTs to this single URL.\n' : ''}

## Setup

\`\`\`tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const queryClient = new QueryClient();

export function Providers({ children }: { children: React.ReactNode }) {
  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;
}
\`\`\`

## Usage

${usageSections.join('\n\n')}

## Folder structure

\`\`\`
api/            infrastructure (client, query keys)
types/          TypeScript interfaces
validators/     Zod schemas, grouped by resource
services/       Axios service classes, grouped by resource
hooks/          React Query hooks, grouped by resource
mocks/          MSW handlers + factory data for local development
\`\`\`
`;

  return { path: 'docs/README.md', content };
}

function defaultArgLiteral(tsType: string): string {
  if (tsType === 'number') return '1';
  if (tsType === 'boolean') return 'true';
  return "'id'";
}
